build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base-debian:bookworm
  amd64: ghcr.io/home-assistant/amd64-base-debian:bookworm
  armv7: ghcr.io/home-assistant/armv7-base-debian:bookworm

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Claude Terminal"
  org.opencontainers.image.description: "Terminal interface for Anthropic's Claude Code CLI"
  org.opencontainers.image.source: "https://github.com/anthropics/claude-code"
  org.opencontainers.image.licenses: "MIT"